{
    'name': 'School Management',
    'application': True,
    'version': '18.0.1.0.0',
    'author': "Alan John",
    'category': 'Education',
    'summary': 'THIS IS UPDATED',
    'depends': ['mail', 'base', 'sale_management', 'contacts', 'base_automation', 'website'],
    'data': [
        'security/res.groups.xml',
        'security/ir.model.access.csv',
        'security/ir.rule.xml',
        'data/sequence_data.xml',
        'data/ir_cron_data.xml',
        'data/mail_template_data.xml',
        'data/base_automation_data.xml',
        'data/student_website_data.xml',
        'data/thankyou_data.xml',
        'wizard/display_wizard_view.xml',
        'views/sale_order_state_views.xml',
        'views/school_student_views.xml',
        'views/school_department_view.xml',
        'views/school_class_view.xml',
        'views/school_subject_view.xml',
        'views/school_academic_year_view.xml',
        'views/school_club_view.xml',
        'views/school_event_view.xml',
        'views/school_teacher_view.xml',
        'views/school_leave_views.xml',
        'views/school_exam_views.xml',
        'views/school_papers_views.xml',
        'views/website_event_views.xml',
        'views/website_menu_views.xml',
        'views/school_menu_list.xml',
        'report/leave_report_template.xml',
        'report/student_report_template.xml',
        'report/school_report.xml',
    ],

    'assets': {
        'web.assets_backend': [
            'school/static/src/js/action_manager.js',
        ],
        'web.assets_frontend': [
            'school/static/src/js/school_website_student.js',
            'school/static/src/js/school_website_events.js',
            'school/static/src/xml/basic.xml',
        ],
    },
}
# -*- coding: utf-8 -*-
